PATH_TO_DATA: null
EXPERIMENT_ID: null
DATA_PATH_PREFIX: "optimized_linear"
TASK: "letter_reconstruction_joints"
KEY: "spindle_FR"
RETRAIN: False
START_END_IDX: [0, 30000]
CAUSAL: True
BATCH_SIZE: 64
spindle_dataset: True
build_fc: False
layer_norm: False