num_i_a: 5
num_ii: 5
chunk_size: 1000
time_steps: 1152
label_dims: 7
output_prefix: "optimized_linear"
i_a_coeff_path: "data/spindle_coefficients/i_a/linear/coefficients.csv"
ii_coeff_path: "data/spindle_coefficients/ii/linear/coefficients.csv"
i_a_sampled_coeff_path: "data/spindle_coefficients/i_a/linear/sampled_coefficients_i_a_5_0.csv" 
ii_sampled_coeff_path: "data/spindle_coefficients/ii/linear/sampled_coefficients_ii_5_0.csv" 
seed: 0 
save_vel: false
sampling_rate: 240
optimal_lengths: [
    93.2,
    97.6,
    107.8,
    136.7,
    75.5,
    254,
    232.4,
    278.9,
    144.2,
    138.5,
    138.5,
    87.3,
    68.2,
    162.4,
    74.1,
    27,
    115.7,
    132.1,
    85.8,
    172.6,
    81,
    49.2,
    113.8,
    134,
    113.8,
]  # List of 25 values
muscles: [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24
] 
